# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/ilarialemmo/Documents/Max\ 8/Packages/max-sdk/source/_smet/tropicaladd~/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/ilarialemmo/Documents/Max\ 8/Packages/max-sdk/source/max-sdk-base/script/max-posttarget.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/ilarialemmo/Documents/Max\ 8/Packages/max-sdk/source/max-sdk-base/script/max-pretarget.cmake))

/Users/ilarialemmo/Documents/Max\ 8/Packages/max-sdk/build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/bin/cmake -H/Users/ilarialemmo/Documents/Max\ 8/Packages/max-sdk -B/Users/ilarialemmo/Documents/Max\ 8/Packages/max-sdk/build
